### ISSUE TITLE
The stream is not complete or contains duplicates if the underlaying table content changes

### ISSUE THREAD

**Issue by bitcloud** [nkovalenko93/sequelize-stream#14]
As this implementation is using offset and limit to iterate over the dataset the result can contain duplicates if a row gets inserted before the current position or skips rows if a row gets deleted before the current position.

You could use a ordered uniq primary key (if available) to continue from.

**Comment by nkovalenko93** [comment]
Try to check version 2.0.2. Added search by primary key if it's autogenerated.

**Comment by nkovalenko93** [comment]
> As this implementation is using offset and limit to iterate over the dataset the result can contain duplicates if a row gets inserted before the current position or skips rows if a row gets deleted before the current position.
> 
> You could use a ordered uniq primary key (if available) to continue from.

Try to check version 2.0.4. Added transaction with SERIALIZABLE isolation level.
