### ISSUE TITLE
Disclaimer

### ISSUE THREAD

**Issue by teobmg** [nkovalenko93/sequelize-stream#24]
In the readme you should add a disclaimer: this library works only if your primary key is a number

**Comment by nkovalenko93** [comment]
Hm. You mean the case when during fetching somebody adds something in the middle of the table? Or some other case?

**Comment by teobmg** [comment]
I mean that if you use an uuid as primary key, the `Op.gt` function will not work, because uuid are randomly generated and not sortable.
With a uuid, you should also use the `created_at` field.

**Comment by nkovalenko93** [comment]
I'll check.

**Comment by nkovalenko93** [comment]
> I mean that if you use an uuid as primary key, the `Op.gt` function will not work, because uuid are randomly generated and not sortable. With a uuid, you should also use the `created_at` field.

Try to check version 2.0.4.
