### ISSUE TITLE
Readable stream in Object mode?

### ISSUE THREAD

**Issue by miketeix** [nkovalenko93/sequelize-stream#4]
Hi there, I see the stream is outputting buffers. Would you be into having the option outputting javascript objects?
It'd be as simple as adding `objectMode: true` when creating the Readable streams, I could make a PR with the change and an optional config param if you'd like.
Thanks!
Mike

**Comment by nkovalenko93** [comment]
@miketeix, Hi. When I'll have some free time I could review and implement. But it'll be better if you make a PR.

**Comment by nkovalenko93** [comment]
@miketeix, Finally I added the object mode in version `1.1.0` :)
