### ISSUE TITLE
Cannot use "attributes" param

### ISSUE THREAD

**Issue by LucCADORET** [nkovalenko93/sequelize-stream#5]
When performing a basic findAllWithStream request, the "attributes" param will cause an error in the underlying function, at the moment where model.count(...) is called. The reason is that when you explicitely specify the attributes, they will be thrown into the count query, this making it invalid.

`        let stream = this.candlesRepository.findAllWithStream({
            attributes: [
                'foo',
            ],
            where: {
                timestamp: {
                    [Op.gte]: since
                }
            },
            order: [['timestamp', 'ASC']]
        });`

Will generate the query

`SELECT "foo", count(*) AS "count" FROM "candles" AS "candle" WHERE  "candle"."timestamp" >= '1970-01-01 00:00:00.000 +00:00`

Which will throw an error, because "foo" is not grouped by, and makes the query invalid.

`original: error: column "candle.foo" must appear in the GROUP BY clause or be used in an aggregate function`

Suggestion: when performing the model.count() call, exclude attributes params.

**Comment by nkovalenko93** [comment]
> When performing a basic findAllWithStream request, the "attributes" param will cause an error in the underlying function, at the moment where model.count(...) is called. The reason is that when you explicitely specify the attributes, they will be thrown into the count query, this making it invalid.
> 
> ` let stream = this.candlesRepository.findAllWithStream({ attributes: [ 'foo', ], where: { timestamp: { [Op.gte]: since } }, order: [['timestamp', 'ASC']] });`
> 
> Will generate the query
> 
> `SELECT "foo", count(*) AS "count" FROM "candles" AS "candle" WHERE "candle"."timestamp" >= '1970-01-01 00:00:00.000 +00:00`
> 
> Which will throw an error, because "foo" is not grouped by, and makes the query invalid.
> 
> `original: error: column "candle.foo" must appear in the GROUP BY clause or be used in an aggregate function`
> 
> Suggestion: when performing the model.count() call, exclude attributes params.

Thank you, I'll fix it during this week or you can make a pull request.

**Comment by nkovalenko93** [comment]
@LucCADORET, Released version 1.0.10.
