### ISSUE TITLE
Streamer now stopped the queries to DB

### ISSUE THREAD

**Issue by talpazflipkart** [nkovalenko93/sequelize-stream#9]
Hi,

We are using you node-sequelize-stream library and it's works great.
we have scenario on our system when we need to abort the process from the client side.
in this scenario, we want the streaming process to stop and not to send any other chunk queries to DB.
we used the destroy() method on the object and it's really send us to the "error" event and the process is stopped.
but, the queries continue to go to DB and we see it in our logs and also the process not free the memory. 
we tested it in window and also in ngnix. both - same behavior.

can you please advise ?

Thanks,
Tal

**Comment by nkovalenko93** [comment]
@talpazflipkart , Hello. Could you please create some simple project with the problem and describe how do you want it to work? Then I'll check it and add some changes.

**Comment by nkovalenko93** [comment]
@talpazflipkart, Released version `1.1.1`. Hope it helps.
